#Kotlin
kotlin.code.style=official
kotlin.daemon.jvmargs=-Xmx3072M

#Gradle
org.gradle.jvmargs=-Xmx4096M -Dfile.encoding=UTF-8
org.gradle.configuration-cache=true
org.gradle.caching=true

#Android
android.nonTransitiveRClass=true
android.useAndroidX=true


GROUP=io.github.moashrafff
VERSION_NAME=0.0.1

# If you want artifactId different from the module name, set this:
POM_ARTIFACT_ID=chatia-ui-components

# Optional but recommended POM fields (used by the pom {} above, or by the plugin?s defaults)
POM_NAME=Chatia UI Components
POM_DESCRIPTION=Reusable UI components for Kotlin Multiplatform using Jetpack Compose
POM_URL=https://github.com/moashrafff/Chatia-ui-components
POM_SCM_URL=https://github.com/moashrafff/Chatia-ui-components
POM_SCM_CONNECTION=scm:git:git://github.com/moashrafff/Chatia-ui-components.git
POM_SCM_DEV_CONNECTION=scm:git:ssh://git@github.com/moashrafff/Chatia-ui-components.git
POM_LICENSE_NAME=The Apache License, Version 2.0
POM_LICENSE_URL=https://www.apache.org/licenses/LICENSE-2.0.txt
POM_DEVELOPER_ID=moashrafff
POM_DEVELOPER_NAME=Mohamed Ashraf
POM_DEVELOPER_URL=https://github.com/moashrafff